### ISSUE TITLE
`TorchModel` improvements

### ISSUE THREAD

**Issue by SergeyTsimfer** [analysiscenter/batchflow#612]
- [x] [Done in #630] Allow more values for `fetches` parameters, e.g. ones from `get_intermediate_activations`

- [x] [Done in #630] Remove `feed_dict` parameter for `train` and `predict`
- [x] [Done in #630] Make logic of `output` more torch-like, not tf-like as it is now
- [x]  Allow `model` key instead of `initial_block/body/head` logic
- [x]  Init functions?

**Comment by SergeyTsimfer** [comment]
Add checks for `batch_size` / `microbatch` in train: don't throw away parts of the batch

**Comment by SergeyTsimfer** [comment]
Fix current slow model tests and add more: for multi-input / multi-output models
